### ISSUE TITLE
.column-50 not working on mobile

### ISSUE THREAD

**Issue by juanbrujo** [milligram/milligram#190] opened 2018-02-22 14:33 UTC
### Version info

v.1.3.0

### Test case

I'm testing right from the source of milligram.io

### Steps to reproduce
I want to have 2 columns, 50 equally distributed in all resolutions. Breaks in mobile, even having 50% width.

```
<div class="row">
  <div class="column column-50">
    <span class="column-demo">.column-50</span>
  </div>
  <div class="column column-50">
    <span class="column-demo">.column-50</span>
  </div>
</div>
```

### Expected behavior

It should be 50% in all resolutions. Desktops ok. as seen:

![screen shot 2018-02-22 at 11 27 07](https://user-images.githubusercontent.com/362186/36543831-b08159aa-17c3-11e8-935b-8721aa4c10b7.png)

### Actual behavior

It doesn't fit, even having `max-width: 50%;`:

![screen shot 2018-02-22 at 11 31 48](https://user-images.githubusercontent.com/362186/36543959-01656f96-17c4-11e8-9110-41010ed37391.png)

**Comment by magikstm** [comment] 2018-03-11 06:18
Not a bug.

It is because of this:

> The Grid is a fluid system with a max width of 112.0rem (1120px), that shrinks with the browser/device at smaller sizes. The max width can be changed with one line of CSS and all columns will resize accordingly.

Ref: https://milligram.io/grids.html

You need to adjust this line accordingly: https://github.com/milligram/milligram/blob/dbbb625aa81ed6119b0f61d16d0a4f4333b526d3/dist/milligram.css#L274

**Comment by juanbrujo** [comment] 2018-03-12 21:04
thanks, it's not about the `max-width`, but the columns breaking in smaller resolutions.

**Comment by magikstm** [comment] 2018-03-12 22:42
I think it's related.

See: https://milligram.io/#tips (under: Tips > Mobile First)

**Comment by JohnGallego** [comment] 2019-10-14 19:50
This is the pertinent code:

https://github.com/milligram/milligram/blob/dbbb625aa81ed6119b0f61d16d0a4f4333b526d3/dist/milligram.css#L431-L441

Flex-direction is changed to column below a certain width.

**Comment by cjpatoilo** [comment] 2020-05-20 04:26
@juanbrujo 
Some trick worked for you or is there still a problem?

**Comment by juanbrujo** [comment] 2020-06-03 14:13
@cjpatoilo I made it (added it) fully responsive and being used a lot without problems.

**Comment by cjpatoilo** [comment] 2020-06-04 02:43
@juanbrujo great! Now I will close this issue. 
If you need any help feel free to reopen this issue or open a new one

**Closed by cjpatoilo** 2020-06-04 02:43 UTC
Labels: Hacktoberfest
