### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by equinusocio** [milligram/milligram#139] opened 2016-12-21 11:35 UTC
How 16 sass files (mostly reset css) can be considered as a "framework?" This is much like a boilerplate/scaffold/starter-kit

**Comment by joelwallis** [comment] 2016-12-21 17:29
https://en.wikipedia.org/wiki/Software_framework

**Comment by equinusocio** [comment] 2016-12-21 18:27
This "framework" is so minimal that you need to rewrite it everytime to get a decent customization.

**Comment by equinusocio** [comment] 2016-12-21 18:28
And, you can rewrite his css in 1hr, with your desired customizations. So i don't see any help from this..

**Comment by nateberkopec** [comment] 2016-12-21 18:43
@equinusocio Do you often open up issues on open source projects just to shit on them? When someone donated their own time to give something to the world for free?

You don't find this project useful. Great. Good for you. 4,653 other people do. Opening unconstructive issues like this only waste's peoples time and discourages maintainers.

<img width="139" alt="screen shot 2016-12-21 at 11 42 34 am" src="https://cloud.githubusercontent.com/assets/845662/21401722/9474bc2c-c772-11e6-8706-63e41cf5adc1.png">

**Comment by sudheerDev** [comment] 2016-12-21 18:49
@equinusocio manners dude!. You can do this in an hour great!. You can make a framework in a day awesome!. Please do it. It will help a lot of developers and projects out there. 

If you dont find this useful. You dont have to use it. No one is forcing you. Dont criticise some one else's work.

**Comment by equinusocio** [comment] 2016-12-22 12:09
Is a simple question

**Comment by sudheerDev** [comment] 2016-12-22 14:02
@equinusocio 
```
   This "framework" is so minimal that you need to rewrite it everytime to get a decent customization.
```
This isnt a question for one!. 
Neither is this.
```
And, you can rewrite his css in 1hr, with your desired customizations. So i don't see any help from this..
```
So please dont tell me to read again because i did the first time.

Okay lets say this is what you were referring when you say you have a question.

```
How 16 sass files (mostly reset css) can be considered as a "framework?" This is much like a boilerplate/scaffold/starter-kit
```

Number of files or lines of code is not a measure for qualifying as a framework IMHO. I got nothing more to say on this as it doesn't matter to me how its categorised. I know what it offers when to use it. 

P.S: Yes you are an active contributor and it baffles me that you still think this is acceptable way to point something out.

**Comment by equinusocio** [comment] 2016-12-22 14:11
@sudheerDev You missed the first topic?
> How 16 sass files (mostly reset css) can be considered as a "framework?" This is much like a boilerplate/scaffold/starter-kit

**Comment by equinusocio** [comment] 2016-12-22 14:31
People here know how add  "👎" reaction but doesn't know how to answer a simple question.

**Comment by cjpatoilo** [comment] 2016-12-22 15:21
Morning guys! @equinusocio @joelwallis @nateberkopec @sudheerDev

@equinusocio Let me tell you the story about my first contribution to the web. I will show you my thoughts and the principles that I cared about before and how he helped start Milligram. I hope you can draw your conclusions and build your opinion better on the definition you are seeking for Milligram.

Bootstrap, Foundation, BaseCSS, Semantic UI, all are awesome frameworks but all are huge. Even with several CSS lines they did not solve the productivity I wanted. At the time I needed to be very fast and consistent because I knew the business of the company was to make fast deliveries and that's how Milligram was born.

**Design Think** 

I wasted a lot of time resetting CSS properties to customize simple components, and most of the time I did not use 90% of the framework. Milligram has a minimal configuration (only necessary).

**Simplicity**

Milligram was designed for simple use. Some properties such as type family, font size, container size. Just change only a single line and that's it.

**Performance**

Milligram is not a UI framework, it just makes the web elements we already know more sexy. So it has ONLY 2kb (gizipado).

**Clarity**

Another problem I tried to solve was the strange use of abbreviations in classes: .col-xs-, .first, .cf .. Abbreviations is not so cool. Milligram makes use of some well-defined classes: .button, .column, .float-left, .float-right. .clearfix.

**Grid**

So far we did not have adequate layout support. Milligram uses the awesome features of CSS3 (Flexbox) for grids. Without limits of 12, 16, 24 .. as well as on the direction: left, right, down, up .. there being a lot more possibilities for customizing.

So this project was born of a personal need. I always try to improvement my production time. I'm literally obsessed with performance and productivity in all my time. I hope it helps you as much as it helps me.

**Comment by cjpatoilo** [comment] 2016-12-22 15:27
For now I will close this issue. Already wasted a lot of energy on an impertinent content that did not add any value to the project. 

@equinusocio Feel free to reopen this issue if this doesn't do the trick for you.

**Closed by cjpatoilo** 2016-12-22 15:27 UTC

**Comment by equinusocio** [comment] 2016-12-22 16:01
@cjpatoilo thanks for gave me a real answer.

> Design Think
I wasted a lot of time resetting CSS properties to customize simple components, and most of the time I did not use 90% of the framework. Milligram has a minimal configuration (only necessary).

This "only necessary" is a bit equivocal, because i think that this "necessary" is not enough in a real context. I made a couple of frameworks during my career, and I agree with you that Bootstrap and other fws are huge (i don't like any of this frameworks) but when you need to build a custom UI component you have to write a lot of css. Think a simple modal component, if you want it on milligram you have to write it, other fws provide this component and youhave only to customize it.

In real website, if are not building a very-ultra-minimal UI Milligram become useless, or it become a simple starter-kit, not a framework. Isn't Milligram a very-specific "framework/boilerplate"? What do you think?

**Comment by joelwallis** [comment] 2016-12-22 18:23
@equinusocio just wondering: what is your doubt? And, if Milligram is not a framework - let's say it's something else, what are you trying to do/accomplish with this issue?

**Comment by overcatbe** [comment] 2020-06-27 14:53
I do not really know how i came to this thread (google), but there is no better place to say THANK YOU, joelwallis, as your work is still great, working and useful! I really like to write the other stuff by myself, using no bloated frameworks, and your work is the perfect basic boilerplate.
