### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by luisaceituno** [milligram/milligram#122] opened 2016-10-10 15:07 UTC
### Version info

**Milligram:** 1.1.0

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):** 
    "dependencies": {
        "normalize.css": "latest"
    },
    "devDependencies": {
        "autoprefixer": "^6.3.6",
        "backstopjs": "^1.3.5",
        "browser-sync": "^2.13.0",
        "node-sass": "^3.7.0",
        "npm-run-all": "^2.1.1",
        "onchange": "^2.4.0",
        "postcss-cli": "^2.5.2",
        "sass-lint": "^1.8.2"
    }

Windows 10, node v6.5.0, npm 3.10.3
### Steps to reproduce
1. Use Windows
2. Clone project
3. run `npm run build` 
### Expected behavior

Build is successful.
### Actual behavior

Following error:
`postcss -u autoprefixer --no-map.inline --autoprefixer.browsers 'last 1 versions' -r dist/*.css`

[system_path]\milligram\node_modules\minimatch\minimatch.js:108
    throw new TypeError('glob pattern string required')
    ^

TypeError: glob pattern string required
    at new Minimatch ([system_path]\milligram\node_modules\minimatch\minimatch.js:108:11)
    at setopts ([system_path]\milligram\node_modules\postcss-cli\node_modules\glob\common.js:112:20)
    at new GlobSync ([system_path]\milligram\node_modules\postcss-cli\node_modules\glob\sync.js:38:3)
    at Function.globSync [as sync]([system_path]milligramnode_modulespostcss-clinode_modulesglobsync.js:24:10)
    at [system_path]\milligram\node_modules\postcss-cli\node_modules\globby\index.js:55:35
    at Array.reduce (native)
    at Function.module.exports.sync ([system_path]\milligram\node_modules\postcss-cli\node_modules\globby\index.js:54:19)
    at Object.<anonymous> ([system_path]\milligram\node_modules\postcss-cli\index.js:90:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)

**Comment by cjpatoilo** [comment] 2016-11-11 06:43
Hey @luisaceituno 

I just update the version. Let us know if you need anything else.
For now, I will close this issue.

**Comment by mmdsharifi** [comment] 2016-11-19 08:07
in version `1.2.0` and node `6.9.1`, npm `3.10.9`  have same error.

after install autoprefixer globally it still have above error. and `banner` have this error:

```
> milligram@1.2.0 banner G:\Github\FinalProject\milligram
> for m in dist/*.css; do echo '/*!
 * Milligram v1.2.0
 * http://milligram.github.io
 *
 * Copyright (c) 2016 CJ Patoilo
 * Licensed under the MIT license
*/
' | cat - $m > temp && mv temp $m; done
m was unexpected at this time.
.
.
.
```

**Comment by cjpatoilo** [comment] 2016-11-19 18:50
Hi @mmdsharifi 

So Milligram use npm scripts for build system. You will not need to install any global dependencies. You only need to have the latest version of [Node](https://nodejs.org/en/download/current/) installed and run `npm start` or` npm install`.

Let us know if you need anything else.

**Comment by cjpatoilo** [comment] 2016-11-22 10:19
@luisaceituno @mmdsharifi I'm working to solve this problem. I added the AppVeyor service to ensure build quality in Windows environments. To follow, just access this link:
https://ci.appveyor.com/project/cjpatoilo/milligram

**Comment by cjpatoilo** [comment] 2016-12-02 17:01
@luisaceituno @mmdsharifi 

I solved the problem generated by single quotation marks in the auprefixer task. There is now an error in the task banner. In summary the problem is about the variation of shell script commands in Windows and MacOS / Linux environments. I've created a module written in Node.js to try to solve this problem, but I need more free time to work on it.

If you can help in any way .. here is the link: https://github.com/cjpatoilo/banner-cli

**Comment by cjpatoilo** [comment] 2016-12-13 05:41
@luisaceituno @mmdsharifi Thank you for reporting this issue. I just extended the node's support. Everything is working well. I'll close this issue but I hope you keep in touch should you need to.

**Closed by cjpatoilo** 2016-12-13 05:41 UTC
Labels: bug
